<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Tiếng Việt (Vietnam)
// Author of the language pack : XTDV Group
// Language pack translators website : http://www.xtdv-group.com/
// Compatible version of MyBB : 1801
// Last edited in MyBB Editor by : truongtx8
// Last edited date : Sun, 26 Oct 2014 12:48:57 +0000
// --------------------------------------------------------------------------------

$l['archive_fullversion'] = 'Phiên bản đầy đủ:';
$l['archive_replies'] = 'Trả lời';
$l['archive_reply'] = 'Trả lời';
$l['archive_pages'] = 'Trang:';
$l['archive_note'] = 'Bạn đang xem phiên bản thu gọn và tối giản. <a href="{1}">Xem phiên bản đầy đủ</a> với định dạng rõ ràng.';
$l['archive_reference_urls'] = '';
$l['archive_nopermission'] = 'Xin lỗi, bạn không có quyền truy cập vào tài nguyên này.';
$l['error_nothreads'] = 'Hiện tại không có chủ đề nào trong diễn đàn này.';
$l['error_unapproved_thread'] = 'This thread is unapproved. Please <a href="{1}">view the full version</a> to view the contents of this thread.';
$l['archive_not_found'] = 'Không tìm thấy trang bạn yêu cầu trên máy chủ.';
$l['error_mustlogin'] = 'Diễn đàn yêu cầu tất cả mọi người phải đăng nhập.';
