<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Tiếng Việt (Vietnam)
// Author of the language pack : XTDV Group
// Language pack translators website : http://www.xtdv-group.com/
// Compatible version of MyBB : 1801
// Last edited in MyBB Editor by : truongtx8
// Last edited date : Sun, 26 Oct 2014 12:48:24 +0000
// --------------------------------------------------------------------------------

$l['post_thread'] = 'Tạo chủ đề';
$l['moderated_by'] = 'Điều hành viên:';
$l['nothreads'] = 'Rất tiếc, hiện không có bài viết hoặc chủ đề nào trong khoảng thời gian đã chọn ở dưới.';
$l['search_forum'] = 'Tìm trong diễn đàn:';
$l['thread'] = 'Chủ đề';
$l['author'] = 'Tác giả';
$l['replies'] = 'Phản hồi';
$l['views'] = 'Xem';
$l['lastpost'] = 'Bài gửi cuối';
$l['rating'] = 'Đánh giá';
$l['markforum_read'] = 'Đánh dấu đã đọc tất cả';
$l['subscribe_forum'] = 'Theo dõi diễn đàn này';
$l['unsubscribe_forum'] = 'Bỏ theo dõi diễn đàn này';
$l['clear_stored_password'] = 'Clear stored forum password';
$l['sort_by_subject'] = 'Sắp xếp theo: Chủ đề';
$l['sort_by_lastpost'] = 'Sắp xếp theo: Bài gửi cuối';
$l['sort_by_starter'] = 'Sắp xếp theo: Tác giả';
$l['sort_by_started'] = 'Sắp xếp theo: Thời gian tạo';
$l['sort_by_rating'] = 'Sắp xếp theo: Đánh giá';
$l['sort_by_replies'] = 'Sắp xếp theo: Phản hồi';
$l['sort_by_views'] = 'Sắp xếp theo: Lượt xem';
$l['sort_order_asc'] = 'Thứ tự: Tăng dần';
$l['sort_order_desc'] = 'Thứ tự: Giảm dần';
$l['datelimit_1day'] = 'Từ: Hôm nay';
$l['datelimit_5days'] = 'Từ: 5 Ngày trước';
$l['datelimit_10days'] = 'Từ: 10 Ngày trước';
$l['datelimit_20days'] = 'Từ: 20 Ngày trước';
$l['datelimit_50days'] = 'Từ: 50 Ngày trước';
$l['datelimit_75days'] = 'Từ: 75 Ngày trước';
$l['datelimit_100days'] = 'Từ: 100 Ngày trước';
$l['datelimit_lastyear'] = 'Từ: Năm trước';
$l['datelimit_beginning'] = 'Từ: Khi bắt đầu';
$l['new_thread'] = 'Có bài mới';
$l['new_hot_thread'] = 'Chủ đề nóng (Mới)';
$l['posts_by_you'] = 'Có bài của bạn';
$l['no_new_thread'] = 'Không có bài mới';
$l['hot_thread'] = 'Chủ đề nóng (Không mới)';
$l['locked_thread'] = 'Chủ đề đã khóa';
$l['goto_first_unread'] = 'Đến bài chưa đọc đầu tiên';
$l['pages'] = 'Trang:';
$l['pages_last'] = 'cuối cùng';
$l['users_browsing_forum'] = 'Những người đang xem diễn đàn:';
$l['users_browsing_forum_guests'] = '{1} khách';
$l['users_browsing_forum_invis'] = '{1} Thành viên ẩn';
$l['delayed_moderation'] = 'Lên lịch quản lý';
$l['inline_thread_moderation'] = 'Công cụ quản lý:';
$l['close_threads'] = 'Đóng chủ đề';
$l['open_threads'] = 'Mở chủ đề';
$l['stick_threads'] = 'Dán chủ đề lên cao';
$l['unstick_threads'] = 'Hạ chủ đề xuống';
$l['delete_threads'] = 'Xóa chủ đề (vĩnh viễn)';
$l['move_threads'] = 'Di chuyển chủ đề';
$l['approve_threads'] = 'Khôi phục chủ đề';
$l['unapprove_threads'] = 'Xóa chủ đề';
$l['inline_go'] = 'Thực hiện';
$l['clear'] = 'Làm lại';
$l['sub_forums_in'] = 'Diễn đàn nhánh trong \'{1}\'';
$l['forum_rules'] = '{1} - Nội quy';
$l['subforums'] = '<strong>Sub Forums:</strong>';
$l['asc'] = 'tăng';
$l['desc'] = 'giảm';
$l['forum_announcements'] = 'Forum Announcements';
$l['sticky_threads'] = 'Chủ đề quan trọng';
$l['normal_threads'] = 'Chủ đề thường';
$l['icon_dot'] = 'Chứa bài viết của bạn. ';
$l['icon_no_new'] = 'Không có bài viết mới.';
$l['icon_new'] = 'Bài viết mới.';
$l['icon_hot'] = ' Chủ đề hấp dẫn.';
$l['icon_lock'] = ' Chủ đề khóa.';
$l['attachment_count'] = 'Diễn đàn này có 1 tập tin đính kèm.';
$l['attachment_count_multiple'] = 'Diễn đàn này có {1} tập tin đính kèm.';
$l['rss_discovery_forum'] = 'Latest Threads in {1}';
$l['forum_unapproved_posts_count'] = 'There are currently {1} unapproved posts in this forum.';
$l['forum_unapproved_post_count'] = 'There is currently 1 unapproved post in this forum.';
$l['forum_unapproved_threads_count'] = 'There are currently {1} unapproved threads in this forum.';
$l['forum_unapproved_thread_count'] = 'There is currently 1 unapproved thread in this forum.';
$l['thread_unapproved_posts_count'] = 'There are currently {1} unapproved posts in this thread.';
$l['thread_unapproved_post_count'] = 'There is currently 1 unapproved post in this thread.';
$l['page_selected'] = 'All <strong>{1}</strong> threads on this page are selected.';
$l['all_selected'] = 'All <strong>{1}</strong> threads in this forum are selected.';
$l['select_all'] = 'Select all <strong>{1}</strong> threads in this forum.';
$l['clear_selection'] = 'Clear Selection.';
$l['error_containsnoforums'] = 'Sorry but the forum you are currently viewing does not contain any child forums.';
$l['prefix'] = 'Tiền tố:';
$l['prefix_all'] = 'Tiền tố: Bất kỳ/Không tiền tố';
$l['prefix_any'] = 'Tiền tố: Bất kỳ';
$l['prefix_none'] = 'Tiền tố: Không tiền tố';
$l['soft_delete_threads'] = 'Xóa chủ đề';
$l['restore_threads'] = 'Khôi phục chủ để';
$l['inline_edit_description'] = '(Nhấn và giữ để sửa)';
