<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Tiếng Việt (Vietnam)
// Author of the language pack : XTDV Group
// Language pack translators website : http://www.xtdv-group.com/
// Compatible version of MyBB : 1801
// Last edited in MyBB Editor by : truongtx8
// Last edited date : Tue, 28 Oct 2014 04:36:01 +0000
// --------------------------------------------------------------------------------

$l['nav_newreply'] = 'Trả lời';
$l['post_reply_to'] = 'Gửi trả lời tới {1}';
$l['post_new_reply'] = 'Gửi bài trả lời mới';
$l['reply_to'] = 'Trả lời chủ đề: {1}';
$l['post_subject'] = 'Chủ đề:';
$l['your_message'] = 'Nội dung:';
$l['post_options'] = 'Tùy chọn:';
$l['options_sig'] = '<strong>Chữ ký:</strong> thêm chữ ký của bạn. (chỉ dành cho thành viên)';
$l['options_emailnotify'] = '<strong>Thông báo qua Email:</strong> nhận thông báo qua email khi có người hồi âm. (chỉ dành cho thành viên)';
$l['options_disablesmilies'] = '<strong>Tắt mặt cười:</strong> không hiển thị các biểu tượng mặt cười trong bài viết.';
$l['post_reply'] = 'Gửi trả lời';
$l['preview_post'] = 'Xem thử trước';
$l['mod_options'] = 'Moderator Options:';
$l['close_thread'] = '<strong>Close Thread</strong>: prevent further posting in this thread.';
$l['stick_thread'] = '<strong>Stick Thread:</strong> stick this thread to the top of the forum.';
$l['thread_review'] = 'Thread Review (Newest First)';
$l['thread_review_more'] = 'This thread has more than {1} replies. <a href="{2}">Read the whole thread.</a>';
$l['posted_by'] = 'Gửi bởi';
$l['draft_saved'] = 'The new post has successfully been saved as a draft.<br />You will now be taken to your draft listing.';
$l['image_verification'] = 'Image Verification';
$l['verification_note'] = 'Please enter the text within the image on the left in to the text box below. This process is used to prevent automated posts.';
$l['verification_subnote'] = '(case insensitive)';
$l['invalid_captcha'] = 'The image verification code that you entered was incorrect. Please enter the code exactly how it appears in the image.';
$l['error_post_already_submitted'] = 'You have already posted this reply to the specified thread. Please visit the thread to see your reply.';
$l['multiquote_external_one'] = 'You have selected one post outside of this thread.';
$l['multiquote_external'] = 'You have selected {1} posts outside of this thread.';
$l['multiquote_external_one_deselect'] = 'deselect this post';
$l['multiquote_external_deselect'] = 'deselect these posts';
$l['multiquote_external_one_quote'] = 'Quote this post too';
$l['multiquote_external_quote'] = 'Quote these posts too';
$l['redirect_newreply'] = 'Cám ơn bạn, bài trả lời của bạn đã được gửi đi.';
$l['redirect_newreply_moderation'] = 'The administrator has specified that all new posts require moderation. You will now be returned to the thread.';
$l['redirect_newreply_post'] = '<br />Bạn sẽ được chuyển tới bài viết đó ngay bây giờ...';
$l['redirect_newreplyerror'] = 'Sorry, but your reply has been rejected for lack of content. <br />You will now be returned to the thread.';
$l['redirect_threadclosed'] = 'You cannot post replies in this thread because it has been closed by a moderator.';
$l['error_post_noperms'] = 'You don\'t have permission to edit this draft.';
$l['forum_rules'] = '{1} - Rules';
$l['error_stop_forum_spam_spammer'] = 'Sorry, your username or IP address matches that of a known spammer. If you feel this is a mistake, please contact an administrator';
$l['error_stop_forum_spam_fetching'] = 'Sorry, something went wrong verifying your reply against a spammer database. Most likely the database couldn\'t be accessed. Please try again later.';
$l['error_suspendedposting'] = 'Your posting privileges are currently suspended {1}.<br /><br />

Suspension Date: {2}';
$l['error_suspendedposting_temporal'] = 'until {1}';
$l['error_suspendedposting_permanent'] = 'permanently';
