<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Tiếng Việt (Vietnam)
// Author of the language pack : XTDV Group
// Language pack translators website : http://www.xtdv-group.com/
// Compatible version of MyBB : 1801
// Last edited in MyBB Editor by : truongtx8
// Last edited date : Tue, 28 Oct 2014 04:36:31 +0000
// --------------------------------------------------------------------------------

$l['nav_newthread'] = 'Tạo chủ đề';
$l['newthread_in'] = 'Tạo chủ đề trong {1}';
$l['post_new_thread'] = 'Gửi chủ đề mới';
$l['thread_subject'] = 'Tiêu đề';
$l['your_message'] = 'Nội dung:';
$l['post_options'] = 'Tùy chọn gửi:';
$l['options_sig'] = '<b>Chữ ký:</b> kèm thêm chữ ký của bạn (dành cho thành viên).';
$l['options_emailnotify'] = '<b>Email Notification:</b> receive an email whenever there is a new reply. (registered users only)';
$l['options_disablesmilies'] = '<b>Không biểu tượng:</b> không hiển thị các biểu tượng vui nhộn trong bài viết.';
$l['post_thread'] = 'Gửi chủ đề';
$l['preview_post'] = 'Xem trước';
$l['poll'] = 'Thăm dò:';
$l['poll_desc'] = 'Optionally you may attach a poll to this thread.';
$l['poll_check'] = 'I want to post a poll';
$l['num_options'] = 'Number of options:';
$l['max_options'] = '(Maximum: {1})';
$l['mod_options'] = 'Moderator Options:';
$l['close_thread'] = '<b>Close Thread</b>: prevent further posting in this thread.';
$l['stick_thread'] = '<b>Stick Thread:</b> stick this thread to the top of the forum.';
$l['draft_saved'] = 'The new thread has successfully been saved as a draft.<br />You will now be taken to your draft listing.';
$l['image_verification'] = 'Image Verification';
$l['verification_note'] = 'Please enter the text within the image on the left in to the text box below. This process is used to prevent automated posts.';
$l['verification_subnote'] = '(case insensitive)';
$l['invalid_captcha'] = 'The image verification code that you entered was incorrect. Please enter the code exactly how it appears in the image.';
$l['error_post_already_submitted'] = 'You have already posted this thread in this forum. Please visit the forum to see your thread.';
$l['no_prefix'] = '- - - - - - - -';
$l['multiquote_external_one'] = 'You have selected one post from another thread.';
$l['multiquote_external'] = 'You have selected {1} posts from other threads.';
$l['multiquote_external_one_deselect'] = 'deselect this post';
$l['multiquote_external_deselect'] = 'deselect these posts';
$l['multiquote_external_one_quote'] = 'Quote this post too';
$l['multiquote_external_quote'] = 'Quote these posts too';
$l['redirect_newthread'] = 'Cám ơn bạn, chủ đề của bạn đã được gửi đi.';
$l['redirect_newthread_poll'] = '<br />You will now be taken to the poll options and configuration page.';
$l['redirect_newthread_moderation'] = '<br />The administrator has specified that all new threads require moderation. You will now be returned to the thread listing.';
$l['redirect_newthread_thread'] = '<br />Bạn sẽ được chuyển tới chủ đề đó ngay bây giờ....';
$l['invalidthread'] = 'The specified draft does not exist or you don\'t have permission to view it.';
$l['forum_rules'] = '{1} - Rules';
$l['error_stop_forum_spam_spammer'] = 'Sorry, your username or IP address matches that of a known spammer. If you feel this is a mistake, please contact an administrator';
$l['error_stop_forum_spam_fetching'] = 'Sorry, something went wrong verifying your thread against a spammer database. Most likely the database couldn\'t be accessed. Please try again later.';
$l['error_suspendedposting'] = 'Your posting privileges are currently suspended {1}.<br /><br />

Suspension Date: {2}';
$l['error_suspendedposting_temporal'] = 'until {1}';
$l['error_suspendedposting_permanent'] = 'permanently';
