<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Tiếng Việt (Vietnam)
// Author of the language pack : XTDV Group
// Language pack translators website : http://www.xtdv-group.com/
// Compatible version of MyBB : 1801
// Last edited in MyBB Editor by : truongtx8
// Last edited date : Tue, 28 Oct 2014 04:36:56 +0000
// --------------------------------------------------------------------------------

$l['nav_online'] = 'Ai đang trực tuyến?';
$l['nav_onlinetoday'] = 'Danh sách trực tuyến trong ngày';
$l['viewing_announcements'] = 'Đang xem <a href="{1}">{2}</a> Announcements';
$l['viewing_announcements2'] = 'Đang xem Forum Announcements';
$l['viewing_attachment'] = 'Đang xem Attachment';
$l['viewing_attachment2'] = 'Đang xem <a href="attachment.php?aid={1}" target="_blank">Attachment</a> in Thread <a href="{3}">{2}</a>';
$l['viewing_calendar'] = 'Đang xem <a href="calendar.php">Calendar</a>';
$l['viewing_event'] = 'Đang xem Event';
$l['viewing_event2'] = 'Đang xem Event <a href="{1}">{2}</a>';
$l['adding_event'] = '<a href="calendar.php?action=addevent">Adding Event</a>';
$l['editing_event'] = 'Editing Event';
$l['editing_post'] = 'Editing Post';
$l['viewing_forum'] = 'Đang xem Forum';
$l['viewing_forum2'] = 'Đang xem Forum <a href="{1}">{2}</a>';
$l['forum_redirect_to'] = 'Being Redirected To <a href="{1}">{2}</a>';
$l['viewing_index'] = '{1} <a href="index.php">Main Index</a>';
$l['activating_account'] = 'Activating Account';
$l['viewing_profile'] = 'Đang xem Profile';
$l['viewing_profile2'] = 'Đang xem Profile of <a href="{1}">{2}</a>';
$l['registering'] = '<a href="member.php?action=register">Registering</a>';
$l['logging_in'] = '<a href="member.php?action=login">Logging In</a>';
$l['logging_in_plain'] = 'Logging In';
$l['logging_out'] = 'Logging Out';
$l['emailing_user'] = 'Emailing a User';
$l['rating_user'] = 'Rating User';
$l['viewing_memberlist'] = 'Đang xem <a href="memberlist.php">Member List</a>';
$l['viewing_whoposted'] = 'Đang xem Who Posted';
$l['viewing_whoposted2'] = 'Đang xem Who Posted in Thread <a href="{1}">{2}</a>';
$l['marking_read'] = '<a href="misc.php?action=markread&amp;my_post_key={1}">Marking Forums as Read</a>';
$l['viewing_helpdocs'] = 'Đang xem <a href="misc.php?action=help">Help Documents</a>';
$l['viewing_buddylist'] = 'Đang xem <a href="misc.php?action=buddypopup">Buddy List</a>';
$l['viewing_smilies'] = 'Đang xem <a href="misc.php?action=smilies">Smilie List</a>';
$l['viewing_syndication'] = 'Đang xem <a href="misc.php?action=syndication">RSS Syndication</a> Page';
$l['replying_thread'] = 'Replying to Thread';
$l['replying_thread2'] = 'Replying to Thread <a href="{1}">{2}</a>';
$l['posting_thread'] = 'Posting New Thread';
$l['posting_thread2'] = 'Posting New Thread in <a href="{1}">{2}</a>';
$l['viewing_wol'] = 'Đang xem <a href="online.php">Danh sách trực tuyến</a>';
$l['viewing_woltoday'] = 'Đang xem <a href="online.php?action=today">Danh sách trực tuyến trong ngày</a>';
$l['creating_poll'] = 'Creating New Poll';
$l['editing_poll'] = 'Editing a Poll';
$l['viewing_pollresults'] = 'Đang xem Poll Results';
$l['voting_poll'] = 'Voting on a Poll';
$l['using_modtools'] = 'Using Moderator Tools';
$l['sending_pm'] = 'Sending Private Message';
$l['reading_pm'] = 'Đang đọc Private Message';
$l['editing_pmfolders'] = 'Editing PM Folders';
$l['using_pmsystem'] = 'Using PM System';
$l['reporting_post'] = 'Reporting a Post';
$l['searching_forum'] = '<a href="search.php">Searching</a> {1}';
$l['reading_thread'] = 'Đang đọc Thread';
$l['reading_thread2'] = 'Đang đọc Thread <a href="{1}">{2}</a> {3}';
$l['viewing_team'] = 'Đang xem Forum Team';
$l['viewing_stats'] = 'Đang xem Forum Statistics';
$l['updating_profile'] = '<a href="usercp.php?action=profile">Updating Profile</a>';
$l['updating_options'] = '<a href="usercp.php?action=options">Updating Options</a>';
$l['editing_signature'] = '<a href="usercp.php?action=editsig">Editing Signature</a>';
$l['changing_avatar'] = '<a href="usercp.php?action=avatar">Changing Avatar</a>';
$l['viewing_subscriptions'] = 'Đang xem <a href="usercp.php?action=subscriptions">Thread Subscriptions</a>';
$l['viewing_favorites'] = 'Đang xem <a href="usercp.php?action=favorites">Favorite Threads</a>';
$l['editing_pad'] = 'Editing <a href="usercp.php?action=notepad">Personal Pad</a>';
$l['editing_password'] = 'Editing <a href="usercp.php?action=password">Password</a>';
$l['user_cp'] = 'Đang xem <a href="usercp.php">User Control Panel</a>';
$l['viewing_portal'] = 'Đang xem <a href="portal.php">Portal</a> Page';
$l['viewing_noperms'] = 'Đang xem No Permissions Page';
$l['unknown_location'] = '<a href="{1}">Unknown Location</a>';
$l['giving_reputation'] = 'Giving Reputation to <a href="{1}">{2}</a>';
$l['viewing_reputation_report'] = 'Viewing <a href="{1}">{2}\'s Reputation</a>';
$l['member_resendactivation'] = 'Resending Account Activation Email';
$l['member_lostpw'] = 'Retrieving <a href="member.php?action=lostpw">Lost Password</a>';
$l['sending_thread'] = 'Sending a thread to a friend';
$l['guest'] = 'Guest';
$l['page'] = 'Page';
$l['users_online'] = 'Đang trực tuyến';
$l['on_username'] = 'Tên đăng nhập';
$l['time'] = 'Thời gian';
$l['location'] = 'Việc làm';
$l['online_today'] = 'Danh sách trực tuyến trong ngày';
$l['refresh_page'] = 'Làm mới danh sách';
$l['online_online_plural'] = 'users';
$l['online_online_singular'] = 'user';
$l['online_member_plural'] = 'members';
$l['online_member_singular'] = 'member';
$l['online_anon_plural'] = 'are';
$l['online_anon_singular'] = 'is';
$l['online_guest_plural'] = 'guests';
$l['online_guest_singular'] = 'guest';
$l['online_count'] = '{1} {2} active in the past {3} minutes ({4} {5}, {6} of whom {7} invisible, and {8} {9}).';
$l['ip'] = 'IP:';
$l['resolves_to'] = 'Host Name:';
$l['if_resolvable'] = '(if resolvable)';
$l['admin_options'] = 'Admin Options:';
$l['search_regip_users'] = 'Search for users who have registered with this IP';
$l['search_postip_users'] = 'Search for users who have posted with this IP';
$l['lookup'] = '[lookup]';
$l['member_online_today'] = '<strong>1</strong> Member Was Online Today';
$l['members_were_online_today'] = '<strong>{1}</strong> Members Were Online Today';
$l['member_online_hidden'] = ' ({1} member was invisible)';
$l['members_online_hidden'] = ' ({1} members were invisible)';
$l['rating_thread'] = 'Rating thread';
$l['viewing_imcenter'] = 'Đang xem IM Center';
$l['managing_favorites'] = 'Managing Favorite Threads';
$l['managing_subscriptions'] = 'Managing Subscribed Threads';
$l['managing_group'] = 'Managing a User Group';
$l['viewing_modcp'] = 'Đang xem Moderator CP';
$l['viewing_modlogs'] = 'Đang xem Moderator Logs';
$l['managing_announcements'] = 'Managing Announcements';
$l['search_for_user'] = 'Searching for users';
$l['managing_warninglogs'] = 'Managing Warning Logs';
$l['searching_ips'] = 'Searching IPs';
$l['viewing_reports'] = 'Đang xem Reported Posts';
$l['adding_announcement'] = 'Adding an Announcement';
$l['deleting_announcement'] = 'Deleting an Announcement';
$l['editing_announcement'] = 'Editing an Announcement';
$l['managing_modqueue'] = 'Managing Moderation Queue';
$l['editing_user_profiles'] = 'Editing User Profiles';
$l['managing_bans'] = 'Managing Bans';
$l['revoking_warning'] = 'Revoking a warning';
$l['warning_user'] = 'Warning a user';
$l['viewing_warning'] = 'Đang xem a warning';
$l['managing_warnings'] = 'Managing warnings';
$l['changing_dst'] = 'Changing DST Switch';
$l['printing_thread'] = 'Printing a Thread';
$l['printing_thread2'] = 'Printing Thread <a href="{1}">{2}</a>';
$l['managing_buddyignorelist'] = 'Managing Buddy/Ignore List';
$l['viewing_contact_us'] = 'Viewing <a href="contact.php">Contact Us</a>';
$l['viewing_reputation_report2'] = 'Viewing Reputation';
