<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Tiếng Việt (Vietnam)
// Author of the language pack : XTDV Group
// Language pack translators website : http://www.xtdv-group.com/
// Compatible version of MyBB : 1801
// Last edited in MyBB Editor by : truongtx8
// Last edited date : Tue, 28 Oct 2014 04:39:29 +0000
// --------------------------------------------------------------------------------

$l['redirect_threadrated'] = 'Thank you, the thread has been rated successfully. You will now be returned to the thread.';
$l['error_invalidrating'] = 'You have selected an invalid rating for this thread. Please go back and try again.';
$l['error_alreadyratedthread'] = 'Sorry, but you have already rated this thread.';
$l['rating_votes_average'] = '{1} Vote(s) - {2} out of 5 in Average';
$l['one_star'] = '1 star out of 5';
$l['two_stars'] = '2 stars out of 5';
$l['three_stars'] = '3 stars out of 5';
$l['four_stars'] = '4 stars out of 5';
$l['five_stars'] = '5 stars out of 5';
$l['rating_added'] = 'Your rating has been added!';
$l['error_cannotrateownthread'] = 'Sorry, you cannot rate your own thread.';
