<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Tiếng Việt (Vietnam)
// Author of the language pack : XTDV Group
// Language pack translators website : http://www.xtdv-group.com/
// Compatible version of MyBB : 1801
// Last edited in MyBB Editor by : truongtx8
// Last edited date : Tue, 28 Oct 2014 04:40:54 +0000
// --------------------------------------------------------------------------------

$l['report_post'] = '';
$l['report_to_mod'] = 'Báo cáo bài viết này tới điều hành viên';
$l['only_report'] = '';
$l['report_reason'] = 'Lý do bạn báo cáo bài viết này?';
$l['thank_you'] = '';
$l['post_reported'] = '';
$l['report_error'] = '';
$l['no_reason'] = '';
$l['go_back'] = '';
$l['close_window'] = 'Đóng cửa sổ';
$l['report_content'] = 'Report Content';
$l['report_reason_post'] = 'Báo cáo bài viết';
$l['report_reason_profile'] = 'Report Profile';
$l['report_reason_reputation'] = 'Report Reputation';
$l['report_reason_bad'] = 'Inappropriate Content';
$l['report_reason_spam'] = 'Spam Content';
$l['report_reason_rules'] = 'Breaks Forum Rules';
$l['report_reason_wrong'] = 'Wrong Forum';
$l['report_reason_other'] = 'Other';
$l['success_report_voted'] = 'Thanks for reporting this content.<br />A member of the forum team will check your report soon.';
$l['error_report_length'] = 'Please provide a detailed reason for your report.';
$l['error_invalid_report'] = 'This content either does not exist or is not able to be reported.';
$l['error_report_duplicate'] = 'This content has already been reported by another member.<br />You may also report this content below.';
$l['report_reason_other_description'] = 'If \'Other\' please provide a reason for reporting this content.';
