<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Tiếng Việt (Vietnam)
// Author of the language pack : XTDV Group
// Language pack translators website : http://www.xtdv-group.com/
// Compatible version of MyBB : 1801
// Last edited in MyBB Editor by : truongtx8
// Last edited date : Tue, 28 Oct 2014 04:42:08 +0000
// --------------------------------------------------------------------------------

$l['nav_search'] = 'Tìm kiếm';
$l['nav_results'] = 'Kết quả';
$l['pages_last'] = 'sau cùng';
$l['search'] = 'Tìm kiếm';
$l['search_keyword'] = 'Tìm theo từ khóa';
$l['search_username'] = 'Tìm theo tên đăng nhập';
$l['search_entire_post'] = 'tìm trong bài viết';
$l['search_titles_only'] = 'chỉ tìm trong tiêu đề';
$l['match_username'] = 'tìm chính xác';
$l['search_forums'] = 'Tìm trong các diễn đàn';
$l['search_all_forums'] = 'Tìm tất các các Diễn đàn';
$l['search_options'] = 'Các tùy chọn';
$l['threads_at_least'] = 'Tìm chủ đề có ít nhất';
$l['threads_at_most'] = 'Tìm chủ đề có nhiều nhất';
$l['find_anydate'] = 'Find posts from any post date';
$l['find_yesterday'] = 'Find posts from yesterday';
$l['find_lastweek'] = 'Find posts from a week ago';
$l['find_2weeks'] = 'Find posts from 2 weeks ago';
$l['find_month'] = 'Find posts from a month ago';
$l['find_3months'] = 'Find posts from 3 months ago';
$l['find_6months'] = 'Find posts from 6 months ago';
$l['find_year'] = 'Find posts from a year ago';
$l['and_newer'] = 'và mới hơn';
$l['and_older'] = 'và cũ hơn';
$l['sorting_options'] = 'Tùy chọn sắp xếp';
$l['sort_lastpost'] = 'Sort Results by last post date';
$l['sort_author'] = 'Sort Results by author';
$l['sort_forum'] = 'Sort Results by forum';
$l['sort_in'] = 'theo thứ tự';
$l['sort_asc'] = 'tăng dần';
$l['sort_desc'] = 'giảm dần';
$l['sort_order'] = 'order';
$l['asc'] = 'tăng';
$l['desc'] = 'giảm';
$l['display_options'] = 'Tùy chọn hiển thị';
$l['show_results_as'] = 'Hiển thị kết quả theo';
$l['show_results_threads'] = 'chủ đề';
$l['show_results_posts'] = 'bài viết';
$l['search_results'] = 'Kết quả tìm kiếm';
$l['post'] = 'Post';
$l['author'] = 'Author';
$l['forum'] = 'Forum';
$l['replies'] = 'Replies';
$l['views'] = 'Views';
$l['posted'] = 'Posted';
$l['thread'] = 'Thread';
$l['lastpost'] = 'Last Post';
$l['post_thread'] = 'Thread:';
$l['post_subject'] = 'Post:';
$l['replies2'] = 'phản hồi';
$l['selectall'] = 'Select all the additional results?';
$l['any_prefix'] = 'Find threads with any prefix';
$l['no_prefix'] = 'No prefix';
$l['inline_thread_moderation'] = 'Inline Thread Moderation:';
$l['close_threads'] = 'Close Threads';
$l['open_threads'] = 'Open Threads';
$l['stick_threads'] = 'Stick Threads';
$l['unstick_threads'] = 'Unstick Threads';
$l['delete_threads'] = 'Delete Threads';
$l['move_threads'] = 'Move Threads';
$l['approve_threads'] = 'Approve Threads';
$l['unapprove_threads'] = 'Unapprove Threads';
$l['inline_delete_posts'] = 'Delete Posts';
$l['inline_merge_posts'] = 'Merge Posts';
$l['inline_split_posts'] = 'Split Posts';
$l['inline_approve_posts'] = 'Approve Posts';
$l['inline_unapprove_posts'] = 'Unapprove Posts';
$l['inline_post_moderation'] = 'Inline Post Moderation:';
$l['inline_go'] = 'Go';
$l['clear'] = 'Clear';
$l['icon_dot'] = 'Contains posts by you. ';
$l['icon_no_new'] = 'No new posts.';
$l['icon_new'] = 'New posts.';
$l['icon_hot'] = ' Hot thread.';
$l['icon_lock'] = ' Locked thread.';
$l['attachment_count'] = 'This thread contains 1 attachment.';
$l['attachment_count_multiple'] = 'This thread contains {1} attachments.';
$l['goto_first_unread'] = 'Go to first unread post';
$l['page_selected'] = 'All <strong>{1}</strong> results on this page are selected.';
$l['all_selected'] = 'All <strong>{1}</strong> results in this search are selected.';
$l['select_all'] = 'Select all <strong>{1}</strong> results in this search.';
$l['clear_selection'] = 'Clear Selection.';
$l['results'] = 'results';
$l['mod_options'] = 'Moderator Options';
$l['find_all'] = '';
$l['find_only_approved'] = '';
$l['find_only_unapproved'] = '';
$l['redirect_searchresults'] = 'Đang thực hiện yêu cầu tìm kiếm của bạn... <br /> Bạn sẽ nhận được kết quả trong giây lát.';
$l['error_minsearchlength'] = 'One or more of your search terms were shorter than the minimum length. The minimum search term length is {1} characters.<br /><br />If you\'re trying to search for an entire phrase, enclose it within double quotes. For example "The quick brown fox jumps over the lazy dog".';
$l['error_nosearchresults'] = 'Sorry, but no results were returned using the query information you provided. Please redefine your search terms and try again.';
$l['error_no_search_support'] = 'This database engine does not support searching.';
$l['error_nosearchterms'] = 'You did not enter any search terms. At a minimum, you must enter either some search terms or a username to search by.';
$l['error_searchflooding_1'] = 'Sorry, but you can only perform one search every {1} seconds. Please wait another 1 second before attempting to search again.';
$l['error_searchflooding'] = 'Sorry, but you can only perform one search every {1} seconds. Please wait another {2} seconds before attempting to search again.';
$l['error_invalidsearch'] = 'An invalid search was specified.  Please go back and try again.';
$l['inline_soft_delete_posts'] = 'Soft Delete Posts';
$l['inline_restore_posts'] = 'Restore Posts';
$l['search_user'] = 'Search for a user';
$l['display_all'] = 'Display all';
$l['display_only_approved'] = 'Display only approved';
$l['display_only_unapproved'] = 'Display only unapproved';
$l['display_only_softdeleted'] = 'Display only soft deleted';
