<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Tiếng Việt (Vietnam)
// Author of the language pack : XTDV Group
// Language pack translators website : http://www.xtdv-group.com/
// Compatible version of MyBB : 1801
// Last edited in MyBB Editor by : truongtx8
// Last edited date : Tue, 28 Oct 2014 04:42:26 +0000
// --------------------------------------------------------------------------------

$l['nav_sendthread'] = 'Send Thread to a Friend';
$l['send_thread'] = 'Send To Friend';
$l['recipient'] = 'Recipient:';
$l['recipient_note'] = 'Enter your friends email address here.';
$l['subject'] = 'Subject:';
$l['message'] = 'Message:';
$l['error_nosubject'] = 'You are required to enter a subject for the message to send your thread';
$l['error_nomessage'] = 'You are required to enter a message before you can send this thread to your friend';
$l['image_verification'] = 'Image Verification';
$l['verification_subnote'] = '(case insensitive)';
$l['verification_note'] = 'Please enter the text contained within the image into the text box below it. This process is used to prevent automated processes.';
