<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Tiếng Việt (Vietnam)
// Author of the language pack : XTDV Group
// Language pack translators website : http://www.xtdv-group.com/
// Compatible version of MyBB : 1801
// Last edited in MyBB Editor by : truongtx8
// Last edited date : Sun, 26 Oct 2014 12:46:35 +0000
// --------------------------------------------------------------------------------

$l['delete_poll'] = 'Delete Poll';
$l['close_thread'] = 'Close Thread';
$l['stick_thread'] = 'Stick Thread';
$l['author'] = 'Tác giả';
$l['message'] = 'Nội dung';
$l['threaded'] = 'Chế độ đề tài';
$l['linear'] = 'Chế độ thứ tự';
$l['next_oldest'] = 'Bài tiếp (cũ nhất)';
$l['next_newest'] = 'Bài tiếp (mới nhất)';
$l['view_printable'] = 'Xem phiên bản để in';
$l['send_thread'] = 'Gửi đề tài này tới bạn của bạn';
$l['subscribe_thread'] = 'Theo dõi đề tài này';
$l['unsubscribe_thread'] = 'Bỏ theo dõi đề tài này';
$l['moderation_options'] = 'Công cụ quản lý:';
$l['delayed_moderation'] = 'Lên lịch quản lý';
$l['thread_notes'] = 'Edit / View Thread Notes';
$l['open_close_thread'] = 'Open / Close Thread';
$l['approve_thread'] = 'Approve Thread';
$l['unapprove_thread'] = 'Unapprove Thread';
$l['delete_thread'] = 'Xóa chủ để (vĩnh viễn)';
$l['delete_posts'] = 'Delete Selective Posts';
$l['move_thread'] = 'Move / Copy Thread';
$l['stick_unstick_thread'] = 'Stick / Unstick Thread';
$l['split_thread'] = 'Split Thread';
$l['merge_threads'] = 'Merge Threads';
$l['merge_posts'] = '';
$l['remove_redirects'] = 'Remove Redirects';
$l['remove_subscriptions'] = 'Remove All Subscriptions';
$l['poll'] = 'Poll:';
$l['show_results'] = 'Show Results';
$l['edit_poll'] = 'Edit poll';
$l['public_note'] = '<b>Note:</b> This is a public poll, other users will be able to see what you voted for.';
$l['total'] = 'Total';
$l['vote'] = 'Vote!';
$l['total_votes'] = '{1} votes';
$l['you_voted'] = '* You voted for this item.';
$l['poll_closed'] = 'Bình chọn đã đóng.';
$l['already_voted'] = 'You have already voted on this poll.';
$l['undo_vote'] = 'Undo vote';
$l['quick_reply'] = 'Trả lời nhanh';
$l['message_note'] = 'Viết nội dung trả lời của bạn vào đây.';
$l['signature'] = 'Chữ ký';
$l['email_notify'] = 'Thông báo qua Email';
$l['disable_smilies'] = 'Tắt biểu tượng';
$l['post_reply'] = 'Gửi trả lời';
$l['post_reply_img'] = 'Gửi trả lời';
$l['post_thread'] = 'Tạo chủ đề';
$l['preview_post'] = 'Xem trước';
$l['rating_average'] = '{1} Votes - {2} Average';
$l['rate_thread'] = 'Đánh giá chủ đề:';
$l['thread_rating'] = 'Đánh giá chủ đề:';
$l['similar_threads'] = 'Các chủ đề có liên quan...';
$l['thread'] = 'Chủ đề:';
$l['replies'] = 'Trả lời:';
$l['views'] = 'Xem:';
$l['lastpost'] = 'Bài mới gửi';
$l['messages_in_thread'] = 'Messages In This Thread';
$l['users_browsing_thread'] = 'Những người đang xem chủ đề này:';
$l['users_browsing_thread_guests'] = '{1} khách';
$l['users_browsing_thread_invis'] = '{1} người ẩn danh';
$l['users_browsing_thread_reading'] = 'Đang đọc...';
$l['inline_delete_posts'] = 'Xóa bài (vĩnh viễn)';
$l['inline_merge_posts'] = 'Merge Posts';
$l['inline_split_posts'] = 'Split Posts';
$l['inline_approve_posts'] = 'Khôi phục bài viết';
$l['inline_unapprove_posts'] = 'Xóa bài viết';
$l['inline_post_moderation'] = 'Quản lý bài viết:';
$l['inline_go'] = 'Thực hiện';
$l['clear'] = 'Làm lại';
$l['thread_closed'] = 'Chủ đề đóng';
$l['no_subject'] = 'Không có tiêu đề';
$l['error_nonextnewest'] = 'There are no threads that are newer than the one you were previously viewing.';
$l['error_nonextoldest'] = 'There are no threads that are older than the one you were previously viewing.';
$l['quickreply_multiquote_selected'] = 'Bạn đã trích dẫn một hoặc nhiều bài ở trên.';
$l['quickreply_multiquote_now'] = 'Trích dẫn các bài đó ngay';
$l['or'] = 'hoặc';
$l['quickreply_multiquote_deselect'] = 'bỏ trích dẫn';
$l['search_thread'] = 'Tìm trong chủ đề';
$l['enter_keywords'] = 'Nhập từ khóa';
$l['image_verification'] = 'Image Verification';
$l['verification_note'] = 'Please enter the text within the image on the left in to the text box below. This process is used to prevent automated posts.';
$l['verification_subnote'] = '(phân biệt chữ HOA)';
$l['thread_modes'] = 'Chế độ hiển thị';
$l['add_poll_to_thread'] = 'Thêm bình chọn';
$l['soft_delete_thread'] = 'Xóa chủ để';
$l['restore_thread'] = 'Khôi phục chủ đề';
$l['poll_closes'] = 'Bình chọn sẽ đóng vào lúc: {1}';
$l['new_reply'] = 'Trả lời mới';
$l['search_button'] = 'Tìm';
$l['inline_soft_delete_posts'] = 'Xóa bài viết';
$l['inline_restore_posts'] = 'Khôi phục bài viết';
$l['inline_move_posts'] = 'Di chuyển bài viết';
$l['view_thread_notes'] = 'Ghi chú';
$l['view_all_notes'] = 'Xem tất cả ghi chú';
$l['save_changes'] = 'Lưu thay đổi';
$l['cancel_edit'] = 'Hủy bỏ';
$l['quick_edit_update_error'] = 'Có lỗi Xảy ra khi sửa phản hồi của bạn:';
$l['quick_reply_post_error'] = 'Có lỗi Xảy ra khi gửi phản hồi của bạn:';
$l['quick_delete_error'] = 'Có lỗi Xảy ra khi xóa phản hồi của bạn:';
$l['quick_delete_success'] = 'Xóa bài viêt thành công.';
$l['quick_delete_thread_success'] = 'Xóa chủ đề thành công.';
$l['quick_restore_error'] = 'There was an error restoring your reply:';
$l['quick_restore_success'] = 'The post was restored successfully.';
