<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Tiếng Việt (Vietnam)
// Author of the language pack : XTDV Group
// Language pack translators website : http://www.xtdv-group.com/
// Compatible version of MyBB : 1801
// Last edited in MyBB Editor by : truongtx8
// Last edited date : Tue, 28 Oct 2014 04:43:22 +0000
// --------------------------------------------------------------------------------

$l['nav_showteam'] = 'Đội ngũ diễn đàn';
$l['forum_team'] = 'Đội ngũ diễn đàn';
$l['moderators'] = 'Điều hành viên';
$l['mod_username'] = '';
$l['mod_forums'] = 'Diễn đàn';
$l['mod_email'] = '';
$l['mod_pm'] = '';
$l['uname'] = '';
$l['email'] = 'Email';
$l['pm'] = 'Tin nhắn';
$l['group_leaders'] = 'Trưởng nhóm';
$l['group_members'] = 'Thành viên';
$l['no_members'] = 'Không có thành viên nào trong nhóm';
$l['error_noteamstoshow'] = 'Không thể hiển thị đội ngũ diễn đàn.';
$l['username'] = 'Tên đăng nhập';
$l['lastvisit'] = 'Last Visit';
$l['online'] = 'Trực tuyến';
$l['offline'] = 'Ngoại tuyến';
