<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Tiếng Việt (Vietnam)
// Author of the language pack : XTDV Group
// Language pack translators website : http://www.xtdv-group.com/
// Compatible version of MyBB : 1801
// Last edited in MyBB Editor by : truongtx8
// Last edited date : Tue, 28 Oct 2014 04:43:47 +0000
// --------------------------------------------------------------------------------

$l['nav_stats'] = 'Tình trạng diễn đàn';
$l['board_stats'] = 'Thống kê diễn đàn';
$l['none'] = 'Không';
$l['nobody'] = '';
$l['totals'] = 'Tổng cộng';
$l['averages'] = 'Trung bình';
$l['posts'] = 'Bài viết:';
$l['threads'] = 'Chủ đề:';
$l['members'] = 'Thành viên:';
$l['ppd'] = 'Số bài viết mỗi ngày:';
$l['tpd'] = 'Số chủ đề mỗi ngày:';
$l['mpd'] = 'Thành viên mới mỗi ngày:';
$l['ppm'] = 'Số bài mỗi thành viên gửi:';
$l['rpt'] = 'Lượt phản hồi mỗi chủ đề:';
$l['no_posts'] = 'Không';
$l['general'] = 'Tổng quan';
$l['newest_member'] = 'Thành viên mới nhất:';
$l['members_posted'] = 'Thành viên viết bài:';
$l['todays_top_poster'] = 'Người viết nhiều hôm nay: <b>{1}</b> (<b>{2}</b> bài)';
$l['popular_forum'] = 'Diễn đàn nổi bật: <b>{1}</b> (<b>{2}</b> bài, <b>{3}</b> chủ đề)';
$l['most_popular'] = 'Thông tin nổi bật...';
$l['most_replied_threads'] = 'Chủ đề có nhiều phản hồi';
$l['most_viewed_threads'] = 'Chủ đề được chú ý';
$l['not_enough_info_stats'] = 'Sorry, but there is not enough information on this board to generate statistics. Before statistics can be generated this board needs to contain at least 1 member and 1 thread.';
$l['replies'] = 'phản hồi';
$l['views'] = 'lượt xem';
$l['stats_disabled'] = 'You cannot view the statistics page as it has been disabled by the Administrator.';
$l['tpm'] = 'Threads per member:';
$l['top_referrer'] = 'Top referrer: <strong>{1}</strong> (<strong>{2}</strong> referrals)';
