<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Tiếng Việt (Vietnam)
// Author of the language pack : XTDV Group
// Language pack translators website : http://www.xtdv-group.com/
// Compatible version of MyBB : 1801
// Last edited in MyBB Editor by : truongtx8
// Last edited date : Tue, 28 Oct 2014 04:48:33 +0000
// --------------------------------------------------------------------------------

$l['ucp_nav_width'] = '180';
$l['ucp_nav_menu'] = 'Danh mục';
$l['ucp_nav_messenger'] = 'Tin nhắn';
$l['ucp_nav_compose'] = 'Soạn tin';
$l['ucp_nav_tracking'] = 'Theo dõi';
$l['ucp_nav_edit_folders'] = 'Sửa thư mục';
$l['ucp_nav_profile'] = 'Hồ sơ';
$l['ucp_nav_edit_profile'] = 'Sửa hồ sơ';
$l['ucp_nav_edit_options'] = 'Sửa tùy chọn';
$l['ucp_nav_change_email'] = 'Đổi Email';
$l['ucp_nav_change_pass'] = 'Đổi mật khẩu';
$l['ucp_nav_change_username'] = 'Đổi tên đăng nhập';
$l['ucp_nav_edit_sig'] = 'Sửa Chữ ký';
$l['ucp_nav_change_avatar'] = 'Đổi ảnh đại diện';
$l['ucp_nav_misc'] = 'Linh tinh';
$l['ucp_nav_editlists'] = 'Buddy/Ignore List';
$l['ucp_nav_favorite_threads'] = 'Favorite Threads';
$l['ucp_nav_subscribed_threads'] = 'Subscribed Threads';
$l['ucp_nav_forum_subscriptions'] = 'Forum Subscriptions';
$l['ucp_nav_drafts'] = 'Saved Drafts';
$l['ucp_nav_notepad'] = 'Personal Pad';
$l['ucp_nav_view_profile'] = 'View Profile';
$l['ucp_nav_home'] = 'Bảng điều khiển';
$l['ucp_nav_usergroups'] = 'Group Memberships';
$l['ucp_nav_attachments'] = 'Manage Attachments';
$l['ucp_nav_drafts_active'] = '<strong>Saved Drafts ({1})</strong>';
